package ClientDemo;

import Service.ManagementProvider;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;

/**
 *
 * @author martincap
 */
public class ClientDemoFrame extends javax.swing.JFrame {

    private final ManagementProvider mgProvider = new ManagementProvider();
    private final ClientDemoAirplaneAdder adder;

    /**
     * Creates new form ClientDemoFrame
     * @throws java.io.UnsupportedEncodingException
     */
    public ClientDemoFrame() throws UnsupportedEncodingException, IOException {
        this.adder = new ClientDemoAirplaneAdder();
        initComponents();
        initLists();

        this.setVisible(true);
    }

    private void initLists() {
        airplanesList.setSelectionMode(SINGLE_SELECTION);
        updateLists();
    }

    private void updateLists() {
        airplanesList.setListData(mgProvider.getAirplaneManager().findAll().toArray());
    }

    private void updateAirplanesList() {
        airplanesList.setListData(mgProvider.getAirplaneManager().findAll().toArray());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        airplanesPanel = new javax.swing.JPanel();
        airplanesSlider = new javax.swing.JSlider();
        airplanesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        airplanesList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        airplanesSlider.setMajorTickSpacing(1);
        airplanesSlider.setMaximum(10);
        airplanesSlider.setMinimum(1);
        airplanesSlider.setPaintLabels(true);
        airplanesSlider.setPaintTicks(true);
        airplanesSlider.setSnapToTicks(true);
        airplanesSlider.setToolTipText("");
        airplanesSlider.setValue(1);

        airplanesButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        airplanesButton.setText("Add airplanes");
        airplanesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airplanesButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Please select how many airplanes to add:");

        airplanesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(airplanesList);

        javax.swing.GroupLayout airplanesPanelLayout = new javax.swing.GroupLayout(airplanesPanel);
        airplanesPanel.setLayout(airplanesPanelLayout);
        airplanesPanelLayout.setHorizontalGroup(
            airplanesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(airplanesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(airplanesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(airplanesPanelLayout.createSequentialGroup()
                        .addComponent(airplanesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, airplanesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(airplanesSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        airplanesPanelLayout.setVerticalGroup(
            airplanesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(airplanesPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(airplanesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(airplanesSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, airplanesPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)))
                .addComponent(airplanesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Airplanes", airplanesPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void airplanesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airplanesButtonActionPerformed
        adder.addAirplanes(airplanesSlider.getValue());
        updateAirplanesList();
    }//GEN-LAST:event_airplanesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ClientDemoFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ClientDemoFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airplanesButton;
    private javax.swing.JList airplanesList;
    private javax.swing.JPanel airplanesPanel;
    private javax.swing.JSlider airplanesSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
