package ClientDemo;

import Service.ManagementProvider;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;

/**
 *
 * @author martincap
 */
public class ClientDemoFrame extends javax.swing.JFrame {

    private final ManagementProvider mgProvider = new ManagementProvider();
    private final ClientDemoAirplaneAdder airplaneAdder;
    private final ClientDemoAirportAdder airportAdder;
    
    
    private final String prefix = "There are ";
    private final String postfix = " in the database.";

    /**
     * Creates new form ClientDemoFrame
     * @throws java.io.UnsupportedEncodingException
     */
    public ClientDemoFrame() throws UnsupportedEncodingException, IOException {
        this.airplaneAdder = new ClientDemoAirplaneAdder();
        this.airportAdder = new ClientDemoAirportAdder();
        initComponents();
        initLists();
        updateNumAirplanesLabel();
        this.setVisible(true);
    }
    
    private void updateNumAirplanesLabel() {
        numAirplanesLabel.setText(prefix + mgProvider.getAirplaneManager().findAll().size() + " airplanes" + postfix);
    }
    
    private void updateNumAirportsLabel() {
        numAirportsLabel.setText(prefix + mgProvider.getAirportManager().findAll().size() + " airports" + postfix);
    }

    private void initLists() {
        airplanesList.setSelectionMode(SINGLE_SELECTION);
        airportsList.setSelectionMode(SINGLE_SELECTION);
        updateLists();
    }

    private void updateLists() {
        updateAirplanesList();
        updateAirportsList();
    }

    private void updateAirplanesList() {
        airplanesList.setListData(mgProvider.getAirplaneManager().findAll().toArray());
    }
    
    private void updateAirportsList() {
        airportsList.setListData(mgProvider.getAirportManager().findAll().toArray());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        airplanesPanel = new javax.swing.JPanel();
        airplanesSlider = new javax.swing.JSlider();
        airplanesButton = new javax.swing.JButton();
        airplanesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        airplanesList = new javax.swing.JList();
        airplanesRefreshButton = new javax.swing.JButton();
        numAirplanesLabel = new javax.swing.JLabel();
        airportsPanel = new javax.swing.JPanel();
        airportsSlider = new javax.swing.JSlider();
        airportsButton = new javax.swing.JButton();
        airportsLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        airportsList = new javax.swing.JList();
        airportsRefreshButton = new javax.swing.JButton();
        numAirportsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        airplanesSlider.setMajorTickSpacing(1);
        airplanesSlider.setMaximum(10);
        airplanesSlider.setMinimum(1);
        airplanesSlider.setPaintLabels(true);
        airplanesSlider.setPaintTicks(true);
        airplanesSlider.setSnapToTicks(true);
        airplanesSlider.setToolTipText("");
        airplanesSlider.setValue(1);

        airplanesButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        airplanesButton.setText("Add airplanes");
        airplanesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airplanesButtonActionPerformed(evt);
            }
        });

        airplanesLabel.setText("Please select how many airplanes to add:");

        airplanesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(airplanesList);

        airplanesRefreshButton.setText("Refresh data");
        airplanesRefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airplanesRefreshButtonActionPerformed(evt);
            }
        });

        numAirplanesLabel.setText("There are 0 airplanes in the database.");

        javax.swing.GroupLayout airplanesPanelLayout = new javax.swing.GroupLayout(airplanesPanel);
        airplanesPanel.setLayout(airplanesPanelLayout);
        airplanesPanelLayout.setHorizontalGroup(
            airplanesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(airplanesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(airplanesPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(airplanesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, airplanesPanelLayout.createSequentialGroup()
                        .addGroup(airplanesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(airplanesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numAirplanesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(airplanesSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                    .addComponent(airplanesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(airplanesRefreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        airplanesPanelLayout.setVerticalGroup(
            airplanesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(airplanesPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(airplanesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(airplanesLabel)
                    .addGroup(airplanesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(airplanesSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numAirplanesLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(airplanesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(airplanesRefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Airplanes", airplanesPanel);

        airportsSlider.setMajorTickSpacing(1);
        airportsSlider.setMaximum(10);
        airportsSlider.setMinimum(1);
        airportsSlider.setPaintLabels(true);
        airportsSlider.setPaintTicks(true);
        airportsSlider.setSnapToTicks(true);
        airportsSlider.setToolTipText("");
        airportsSlider.setValue(1);

        airportsButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        airportsButton.setText("Add airports");
        airportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airportsButtonActionPerformed(evt);
            }
        });

        airportsLabel.setText("Please select how many airports to add:  ");

        airportsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(airportsList);

        airportsRefreshButton.setText("Refresh data");
        airportsRefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airportsRefreshButtonActionPerformed(evt);
            }
        });

        numAirportsLabel.setText("There are 0 airports in the database.");

        javax.swing.GroupLayout airportsPanelLayout = new javax.swing.GroupLayout(airportsPanel);
        airportsPanel.setLayout(airportsPanelLayout);
        airportsPanelLayout.setHorizontalGroup(
            airportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(airportsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(airportsPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(airportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, airportsPanelLayout.createSequentialGroup()
                        .addGroup(airportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(airportsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numAirportsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(airportsSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                    .addComponent(airportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(airportsRefreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        airportsPanelLayout.setVerticalGroup(
            airportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(airportsPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(airportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(airportsLabel)
                    .addGroup(airportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(airportsSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numAirportsLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(airportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(airportsRefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Airports", airportsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void airplanesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airplanesButtonActionPerformed
        airplaneAdder.addAirplanes(airplanesSlider.getValue());
        updateAirplanesList();
        updateNumAirplanesLabel();
    }//GEN-LAST:event_airplanesButtonActionPerformed

    private void airplanesRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airplanesRefreshButtonActionPerformed
        updateAirplanesList();
        updateNumAirplanesLabel();
    }//GEN-LAST:event_airplanesRefreshButtonActionPerformed

    private void airportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airportsButtonActionPerformed
        airportAdder.addAirplanes(airportsSlider.getValue());
        updateAirportsList();
        updateNumAirportsLabel();
    }//GEN-LAST:event_airportsButtonActionPerformed

    private void airportsRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airportsRefreshButtonActionPerformed
        updateAirportsList();
        updateNumAirportsLabel();
    }//GEN-LAST:event_airportsRefreshButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ClientDemoFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ClientDemoFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airplanesButton;
    private javax.swing.JLabel airplanesLabel;
    private javax.swing.JList airplanesList;
    private javax.swing.JPanel airplanesPanel;
    private javax.swing.JButton airplanesRefreshButton;
    private javax.swing.JSlider airplanesSlider;
    private javax.swing.JButton airportsButton;
    private javax.swing.JLabel airportsLabel;
    private javax.swing.JList airportsList;
    private javax.swing.JPanel airportsPanel;
    private javax.swing.JButton airportsRefreshButton;
    private javax.swing.JSlider airportsSlider;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel numAirplanesLabel;
    private javax.swing.JLabel numAirportsLabel;
    // End of variables declaration//GEN-END:variables
}
