/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

/**
 *
 * @author M
 */
public class AirportAttributesDialog extends javax.swing.JDialog {

    /**
     * Creates new form AirportAttributesDialog
     */
    public AirportAttributesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AirportAttributesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AirportNameLabel = new javax.swing.JLabel();
        AirportNameTextField = new javax.swing.JTextField();
        AirportCityLabel = new javax.swing.JLabel();
        AirportCityTextField = new javax.swing.JTextField();
        AirportIcaoLabel = new javax.swing.JLabel();
        AirportIcaoTextField = new javax.swing.JTextField();
        AirportIataLabel = new javax.swing.JLabel();
        AirportIataTextField = new javax.swing.JTextField();
        AirportCountryTextField = new javax.swing.JTextField();
        AirportCountryLabel = new javax.swing.JLabel();
        OriginScrollPane = new javax.swing.JScrollPane();
        AirportOriginList = new javax.swing.JList();
        DestinationScrollPane = new javax.swing.JScrollPane();
        AirportDestinationList = new javax.swing.JList();
        AirportSaveChanges = new javax.swing.JButton();
        AirportDiscardChanges = new javax.swing.JButton();
        DestinationsLabel = new javax.swing.JLabel();
        OriginsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Airport Attributes");
        setBackground(new java.awt.Color(204, 204, 255));

        AirportAttributesPanel.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Airport Attributes");

        AirportNameLabel.setText("Name:");

        AirportNameTextField.setBackground(new java.awt.Color(52, 52, 56));
        AirportNameTextField.setForeground(new java.awt.Color(255, 255, 255));

        AirportCityLabel.setText("City:");

        AirportCityTextField.setBackground(new java.awt.Color(52, 52, 56));
        AirportCityTextField.setForeground(new java.awt.Color(255, 255, 255));

        AirportIcaoLabel.setText("ICAO");

        AirportIcaoTextField.setBackground(new java.awt.Color(52, 52, 56));
        AirportIcaoTextField.setForeground(new java.awt.Color(255, 255, 255));

        AirportIataLabel.setText("IATA");

        AirportIataTextField.setBackground(new java.awt.Color(52, 52, 56));
        AirportIataTextField.setForeground(new java.awt.Color(255, 255, 255));

        AirportCountryTextField.setBackground(new java.awt.Color(52, 52, 56));
        AirportCountryTextField.setForeground(new java.awt.Color(255, 255, 255));
        AirportCountryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirportCountryTextFieldActionPerformed(evt);
            }
        });

        AirportCountryLabel.setText("Country:");

        javax.swing.GroupLayout AirportAttributesPanelLayout = new javax.swing.GroupLayout(AirportAttributesPanel);
        AirportAttributesPanel.setLayout(AirportAttributesPanelLayout);
        AirportAttributesPanelLayout.setHorizontalGroup(
            AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AirportAttributesPanelLayout.createSequentialGroup()
                .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AirportAttributesPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(AirportAttributesPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AirportNameLabel)
                            .addComponent(AirportCityLabel)
                            .addComponent(AirportIcaoLabel)
                            .addComponent(AirportIataLabel)
                            .addComponent(AirportCountryLabel))
                        .addGap(18, 18, 18)
                        .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AirportCountryTextField)
                            .addComponent(AirportIataTextField)
                            .addComponent(AirportIcaoTextField)
                            .addComponent(AirportCityTextField)
                            .addComponent(AirportNameTextField))))
                .addGap(25, 25, 25))
        );
        AirportAttributesPanelLayout.setVerticalGroup(
            AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AirportAttributesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirportNameLabel)
                    .addComponent(AirportNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirportCityLabel)
                    .addComponent(AirportCityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirportIcaoLabel)
                    .addComponent(AirportIcaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirportIataLabel)
                    .addComponent(AirportIataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirportCountryLabel)
                    .addComponent(AirportCountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        AirportOriginList.setBackground(new java.awt.Color(204, 204, 255));
        AirportOriginList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        OriginScrollPane.setViewportView(AirportOriginList);

        AirportDestinationList.setBackground(new java.awt.Color(204, 204, 255));
        AirportDestinationList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        DestinationScrollPane.setViewportView(AirportDestinationList);

        AirportSaveChanges.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AirportSaveChanges.setText("Save changes");
        AirportSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirportSaveChangesActionPerformed(evt);
            }
        });

        AirportDiscardChanges.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AirportDiscardChanges.setForeground(new java.awt.Color(179, 107, 12));
        AirportDiscardChanges.setText("Discard changes");
        AirportDiscardChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirportDiscardChangesActionPerformed(evt);
            }
        });

        DestinationsLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        DestinationsLabel.setText("This Airport serves as  DESTINATION  in Routes:");

        OriginsLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        OriginsLabel.setText("This Airport serves as  ORIGIN  in Routes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DestinationsLabel)
                    .addComponent(OriginsLabel)
                    .addComponent(OriginScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(DestinationScrollPane))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AirportAttributesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AirportDiscardChanges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AirportSaveChanges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirportSaveChanges)
                    .addComponent(OriginsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AirportDiscardChanges)
                        .addGap(8, 8, 8)
                        .addComponent(AirportAttributesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OriginScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DestinationsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DestinationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AirportSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirportSaveChangesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirportSaveChangesActionPerformed

    private void AirportDiscardChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirportDiscardChangesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirportDiscardChangesActionPerformed

    private void AirportCountryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirportCountryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirportCountryTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirportAttributesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirportAttributesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirportAttributesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirportAttributesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AirportAttributesDialog dialog = new AirportAttributesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AirportAttributesPanel;
    private javax.swing.JLabel AirportCityLabel;
    private javax.swing.JTextField AirportCityTextField;
    private javax.swing.JLabel AirportCountryLabel;
    private javax.swing.JTextField AirportCountryTextField;
    private javax.swing.JList AirportDestinationList;
    private javax.swing.JButton AirportDiscardChanges;
    private javax.swing.JLabel AirportIataLabel;
    private javax.swing.JTextField AirportIataTextField;
    private javax.swing.JLabel AirportIcaoLabel;
    private javax.swing.JTextField AirportIcaoTextField;
    private javax.swing.JLabel AirportNameLabel;
    private javax.swing.JTextField AirportNameTextField;
    private javax.swing.JList AirportOriginList;
    private javax.swing.JButton AirportSaveChanges;
    private javax.swing.JScrollPane DestinationScrollPane;
    private javax.swing.JLabel DestinationsLabel;
    private javax.swing.JScrollPane OriginScrollPane;
    private javax.swing.JLabel OriginsLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
