/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

/**
 *
 * @author M
 */
public class AirplaneAttributesDialog extends javax.swing.JDialog {

    /**
     * Creates new form AirplaneAttributesDialog
     */
    public AirplaneAttributesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AirportAttributesPanel = new javax.swing.JPanel();
        AirplaneAttributesLabel = new javax.swing.JLabel();
        AirplaneCodeLabel = new javax.swing.JLabel();
        AirplaneCodeTextField = new javax.swing.JTextField();
        AirplaneAirlineLabel = new javax.swing.JLabel();
        AirplaneAirlineTextField = new javax.swing.JTextField();
        AirplaneCapacityLabel = new javax.swing.JLabel();
        AirplaneCapacityTextField = new javax.swing.JTextField();
        AirplaneFuelTankLabel = new javax.swing.JLabel();
        AirplaneFuelTankTextField = new javax.swing.JTextField();
        AirplanePayloadTextField = new javax.swing.JTextField();
        AirplanePayloadLabel = new javax.swing.JLabel();
        AirplaneLoadCapacityLabel = new javax.swing.JLabel();
        AirplaneLoadCapacityTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AirplaneRoutesList = new javax.swing.JList();
        AirplaneDiscardChanges = new javax.swing.JButton();
        AirplaneSaveChanges = new javax.swing.JButton();
        RoutesLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Airplane Attributes");

        AirportAttributesPanel.setBackground(new java.awt.Color(204, 204, 255));

        AirplaneAttributesLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        AirplaneAttributesLabel.setText("Airplane Attributes");

        AirplaneCodeLabel.setText("Code:");

        AirplaneCodeTextField.setBackground(new java.awt.Color(52, 52, 56));
        AirplaneCodeTextField.setForeground(new java.awt.Color(255, 255, 255));

        AirplaneAirlineLabel.setText("Airline:");

        AirplaneAirlineTextField.setBackground(new java.awt.Color(52, 52, 56));
        AirplaneAirlineTextField.setForeground(new java.awt.Color(255, 255, 255));

        AirplaneCapacityLabel.setText("Capacity:");

        AirplaneCapacityTextField.setBackground(new java.awt.Color(52, 52, 56));
        AirplaneCapacityTextField.setForeground(new java.awt.Color(255, 255, 255));

        AirplaneFuelTankLabel.setText("Fuel Tank:");

        AirplaneFuelTankTextField.setBackground(new java.awt.Color(52, 52, 56));
        AirplaneFuelTankTextField.setForeground(new java.awt.Color(255, 255, 255));

        AirplanePayloadTextField.setBackground(new java.awt.Color(52, 52, 56));
        AirplanePayloadTextField.setForeground(new java.awt.Color(255, 255, 255));
        AirplanePayloadTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirplanePayloadTextFieldActionPerformed(evt);
            }
        });

        AirplanePayloadLabel.setText("Payload:");

        AirplaneLoadCapacityLabel.setText("Load capacity:");

        AirplaneLoadCapacityTextField.setBackground(new java.awt.Color(52, 52, 56));
        AirplaneLoadCapacityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirplaneLoadCapacityTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AirportAttributesPanelLayout = new javax.swing.GroupLayout(AirportAttributesPanel);
        AirportAttributesPanel.setLayout(AirportAttributesPanelLayout);
        AirportAttributesPanelLayout.setHorizontalGroup(
            AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AirportAttributesPanelLayout.createSequentialGroup()
                .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AirportAttributesPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(AirplaneAttributesLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(AirportAttributesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AirplaneCodeLabel)
                            .addComponent(AirplaneAirlineLabel)
                            .addComponent(AirplaneCapacityLabel)
                            .addComponent(AirplaneFuelTankLabel)
                            .addComponent(AirplanePayloadLabel)
                            .addComponent(AirplaneLoadCapacityLabel))
                        .addGap(18, 18, 18)
                        .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AirplanePayloadTextField)
                            .addComponent(AirplaneFuelTankTextField)
                            .addComponent(AirplaneCapacityTextField)
                            .addComponent(AirplaneAirlineTextField)
                            .addComponent(AirplaneCodeTextField)
                            .addComponent(AirplaneLoadCapacityTextField))))
                .addContainerGap())
        );
        AirportAttributesPanelLayout.setVerticalGroup(
            AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AirportAttributesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AirplaneAttributesLabel)
                .addGap(18, 18, 18)
                .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirplaneCodeLabel)
                    .addComponent(AirplaneCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirplaneAirlineLabel)
                    .addComponent(AirplaneAirlineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirplaneCapacityLabel)
                    .addComponent(AirplaneCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirplaneFuelTankLabel)
                    .addComponent(AirplaneFuelTankTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirplanePayloadLabel)
                    .addComponent(AirplanePayloadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AirportAttributesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AirplaneLoadCapacityLabel)
                    .addComponent(AirplaneLoadCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AirplaneRoutesList.setBackground(new java.awt.Color(204, 204, 255));
        AirplaneRoutesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(AirplaneRoutesList);

        AirplaneDiscardChanges.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AirplaneDiscardChanges.setForeground(new java.awt.Color(179, 107, 12));
        AirplaneDiscardChanges.setText("Discard changes");
        AirplaneDiscardChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirplaneDiscardChangesActionPerformed(evt);
            }
        });

        AirplaneSaveChanges.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AirplaneSaveChanges.setText("Save changes");
        AirplaneSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirplaneSaveChangesActionPerformed(evt);
            }
        });

        RoutesLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        RoutesLabel.setText("This Airplane flies on Routes:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Find & add new Route to fly on");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RoutesLabel)
                    .addComponent(jScrollPane1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AirportAttributesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AirplaneDiscardChanges, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AirplaneSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirplaneSaveChanges)
                    .addComponent(RoutesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AirplaneDiscardChanges)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AirportAttributesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AirplanePayloadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirplanePayloadTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirplanePayloadTextFieldActionPerformed

    private void AirplaneSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirplaneSaveChangesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirplaneSaveChangesActionPerformed

    private void AirplaneDiscardChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirplaneDiscardChangesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirplaneDiscardChangesActionPerformed

    private void AirplaneLoadCapacityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirplaneLoadCapacityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirplaneLoadCapacityTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirplaneAttributesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirplaneAttributesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirplaneAttributesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirplaneAttributesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AirplaneAttributesDialog dialog = new AirplaneAttributesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AirplaneAirlineLabel;
    private javax.swing.JTextField AirplaneAirlineTextField;
    private javax.swing.JLabel AirplaneAttributesLabel;
    private javax.swing.JLabel AirplaneCapacityLabel;
    private javax.swing.JTextField AirplaneCapacityTextField;
    private javax.swing.JLabel AirplaneCodeLabel;
    private javax.swing.JTextField AirplaneCodeTextField;
    private javax.swing.JButton AirplaneDiscardChanges;
    private javax.swing.JLabel AirplaneFuelTankLabel;
    private javax.swing.JTextField AirplaneFuelTankTextField;
    private javax.swing.JLabel AirplaneLoadCapacityLabel;
    private javax.swing.JTextField AirplaneLoadCapacityTextField;
    private javax.swing.JLabel AirplanePayloadLabel;
    private javax.swing.JTextField AirplanePayloadTextField;
    private javax.swing.JList AirplaneRoutesList;
    private javax.swing.JButton AirplaneSaveChanges;
    private javax.swing.JPanel AirportAttributesPanel;
    private javax.swing.JLabel RoutesLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
