package Application;

import Application.GUIDesigners.DialogDesigner;
import Application.GUIDesigners.Utils;
import ClientDemo.ClientDemoFrame;
import Model.Airplane;
import Model.Airport;
import Model.Route;
import Service.ManagementProvider;
import Validator.InvalidAttributeException;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;
import javax.swing.UIManager;

/**
 *
 * @author Martin
 */
public class ApplicationFrame extends javax.swing.JFrame {

    public ManagementProvider mgProvider;

    //filter Airplanes
    private String filterCode = null;
    private String filterAirline = null;
    private Integer filterMaxPassengerCapacity = null;
    private Integer filterMinPassengerCapacity = null;
    private Integer filterMaxMaximumRange = null;
    private Integer filterMinMaximumRange = null;

    //filter Routes
    private String name1 = null;
    private String name2 = null;
    private String city1 = null;
    private String city2 = null;
    private String country1 = null;
    private String country2 = null;
    private String iata1 = null;
    private String iata2 = null;
    private String icao1 = null;
    private String icao2 = null;

    //filter airports
    private String name = null;
    private String city = null;
    private String country = null;
    private String iata = null;
    private String icao = null;

    /**
     * Creates new form ApplicationFrame
     */
    public ApplicationFrame() {
        initComponents();
        setLocationRelativeTo(null);
        initManagement();
        initLists();
        this.setName("DS Airport");
        // set visible after succesful connection to the database and creation of list data
        this.setVisible(true);
    }

    private void initLists() {
        routejList.setSelectionMode(SINGLE_SELECTION);
        airplanejList.setSelectionMode(SINGLE_SELECTION);
        airportjList.setSelectionMode(SINGLE_SELECTION);
        updateLists();
    }

    private void updateLists() {
        updateAirportList();
        updateAirplaneList();
        updateRouteList();
    }

    private void updateAirportList() {
        airportjList.setListData(mgProvider.getAirportManager().findSpecifiedAlternate(name,
                city, country, icao, iata).toArray());
    }

    private void updateAirplaneList() {
        airplanejList.setListData(mgProvider.getAirplaneManager().findSpecified(
                filterCode, filterAirline,
                filterMaxPassengerCapacity, filterMinPassengerCapacity,
                filterMaxMaximumRange, filterMinMaximumRange).toArray());
    }

    private void updateRouteList() {
        routejList.setListData(mgProvider.getRouteManager().findSpecified(
                city1, city2, name1, name2, icao1, icao2, iata1, iata2, country1, country2).toArray());
    }

    private void initManagement() {
        mgProvider = new ManagementProvider();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        airportPanel = new javax.swing.JPanel();
        createAirportButton = new javax.swing.JButton();
        updateAirportButton = new javax.swing.JButton();
        deleteAirportButton = new javax.swing.JButton();
        applyFilterAirportButton = new javax.swing.JButton();
        airportFilterLabel = new javax.swing.JLabel();
        airportIcaoTextField = new javax.swing.JTextField();
        airportNameTextField = new javax.swing.JTextField();
        airportIataTextField = new javax.swing.JTextField();
        airportCityTextField = new javax.swing.JTextField();
        airportNameLabel = new javax.swing.JLabel();
        airportCityLabel = new javax.swing.JLabel();
        airportIcaoLabel = new javax.swing.JLabel();
        airportIataLabel = new javax.swing.JLabel();
        airportScrollPane = new javax.swing.JScrollPane();
        airportjList = new javax.swing.JList();
        airportCountryLabel = new javax.swing.JLabel();
        airportCountryTextField = new javax.swing.JTextField();
        AirplanePanel = new javax.swing.JPanel();
        updateAirplaneButton = new javax.swing.JButton();
        deleteAirplaneButton = new javax.swing.JButton();
        applyFilterAirplaneButton = new javax.swing.JButton();
        createAirplaneButton = new javax.swing.JButton();
        airplaneFilterLabel = new javax.swing.JLabel();
        airplaneCodeLabel = new javax.swing.JLabel();
        airplaneAirlineLabel = new javax.swing.JLabel();
        airplaneCodeTextField = new javax.swing.JTextField();
        airplaneAirlineTextField = new javax.swing.JTextField();
        airplaneFuelGreaterLabel = new javax.swing.JLabel();
        airplaneFuelLesserLabel = new javax.swing.JLabel();
        airplaneLoadingGreaterLabel = new javax.swing.JLabel();
        airplaneLoadingLesserLabel = new javax.swing.JLabel();
        airplanePassengerGreaterTextField = new javax.swing.JTextField();
        airplanePassengerLesserTextField = new javax.swing.JTextField();
        airplaneRangeGreaterTextField = new javax.swing.JTextField();
        airplaneRangeLesserTextField = new javax.swing.JTextField();
        airplaneScrollPane = new javax.swing.JScrollPane();
        airplanejList = new javax.swing.JList();
        routePanel = new javax.swing.JPanel();
        updateRouteButton = new javax.swing.JButton();
        deleteRouteButton = new javax.swing.JButton();
        applyFilterRouteButton = new javax.swing.JButton();
        createRouteButton = new javax.swing.JButton();
        routeFilterLabel = new javax.swing.JLabel();
        originFilterLabel = new javax.swing.JLabel();
        destinationFilterLabel = new javax.swing.JLabel();
        routeNameLabel1 = new javax.swing.JLabel();
        routeNameLabel2 = new javax.swing.JLabel();
        routeCityLabel1 = new javax.swing.JLabel();
        routeCityLabel2 = new javax.swing.JLabel();
        routeNameTextField1 = new javax.swing.JTextField();
        routeCityTextField1 = new javax.swing.JTextField();
        routeNameTextField2 = new javax.swing.JTextField();
        routeCityTextField2 = new javax.swing.JTextField();
        routeIcaoLabel1 = new javax.swing.JLabel();
        routeIataLabel1 = new javax.swing.JLabel();
        routeIcaoLabel2 = new javax.swing.JLabel();
        routeIataLabel2 = new javax.swing.JLabel();
        routeIcaoTextField1 = new javax.swing.JTextField();
        routeIataTextField1 = new javax.swing.JTextField();
        routeIataTextField2 = new javax.swing.JTextField();
        routeIcaoTextField2 = new javax.swing.JTextField();
        routeScrollPane = new javax.swing.JScrollPane();
        routejList = new javax.swing.JList();
        routeCountryLabel1 = new javax.swing.JLabel();
        routeCountryTextField1 = new javax.swing.JTextField();
        routeCountryLabel2 = new javax.swing.JLabel();
        routeCountryTextField2 = new javax.swing.JTextField();
        clientDemoPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Airport Manager");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(153, 153, 255));
        setLocation(new java.awt.Point(250, 250));
        setLocationByPlatform(true);

        mainTabbedPane.setBackground(new java.awt.Color(204, 204, 255));
        mainTabbedPane.setPreferredSize(new java.awt.Dimension(1024, 768));

        airportPanel.setBackground(new java.awt.Color(204, 204, 255));

        createAirportButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        createAirportButton.setText("Create new");
        createAirportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAirportButtonActionPerformed(evt);
            }
        });

        updateAirportButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        updateAirportButton.setText("Update selected");
        updateAirportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAirportButtonActionPerformed(evt);
            }
        });

        deleteAirportButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        deleteAirportButton.setForeground(new java.awt.Color(137, 25, 25));
        deleteAirportButton.setText("Delete selected");
        deleteAirportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAirportButtonActionPerformed(evt);
            }
        });

        applyFilterAirportButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        applyFilterAirportButton.setForeground(new java.awt.Color(25, 62, 137));
        applyFilterAirportButton.setText("Apply filter");
        applyFilterAirportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyFilterAirportButtonActionPerformed(evt);
            }
        });

        airportFilterLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        airportFilterLabel.setText("Filter settings for Airport:");

        airportIcaoTextField.setBackground(new java.awt.Color(52, 52, 56));
        airportIcaoTextField.setForeground(new java.awt.Color(255, 255, 255));

        airportNameTextField.setBackground(new java.awt.Color(52, 52, 56));
        airportNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        airportNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airportNameTextFieldActionPerformed(evt);
            }
        });

        airportIataTextField.setBackground(new java.awt.Color(52, 52, 56));
        airportIataTextField.setForeground(new java.awt.Color(255, 255, 255));
        airportIataTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airportIataTextFieldActionPerformed(evt);
            }
        });

        airportCityTextField.setBackground(new java.awt.Color(52, 52, 56));
        airportCityTextField.setForeground(new java.awt.Color(255, 255, 255));
        airportCityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airportCityTextFieldActionPerformed(evt);
            }
        });

        airportNameLabel.setText("Name:");

        airportCityLabel.setText("City:");

        airportIcaoLabel.setText("ICAO:");

        airportIataLabel.setText("IATA:");

        airportjList.setBackground(new java.awt.Color(52, 52, 56));
        airportjList.setForeground(new java.awt.Color(255, 255, 255));
        airportjList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        airportScrollPane.setViewportView(airportjList);

        airportCountryLabel.setText("Country:");

        airportCountryTextField.setBackground(new java.awt.Color(52, 52, 56));
        airportCountryTextField.setForeground(new java.awt.Color(255, 255, 255));
        airportCountryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airportCountryTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout airportPanelLayout = new javax.swing.GroupLayout(airportPanel);
        airportPanel.setLayout(airportPanelLayout);
        airportPanelLayout.setHorizontalGroup(
            airportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(airportPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(airportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(airportPanelLayout.createSequentialGroup()
                        .addComponent(airportScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(airportPanelLayout.createSequentialGroup()
                        .addGroup(airportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(airportPanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(airportFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(airportPanelLayout.createSequentialGroup()
                                .addGroup(airportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, airportPanelLayout.createSequentialGroup()
                                        .addComponent(airportNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                        .addComponent(airportNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, airportPanelLayout.createSequentialGroup()
                                        .addGroup(airportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(airportCountryLabel)
                                            .addComponent(airportCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(airportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(airportCityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(airportCountryTextField))))
                                .addGap(18, 18, 18)
                                .addGroup(airportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, airportPanelLayout.createSequentialGroup()
                                        .addComponent(airportIcaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(airportIcaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, airportPanelLayout.createSequentialGroup()
                                        .addComponent(airportIataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(airportIataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                        .addGroup(airportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createAirportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, airportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(applyFilterAirportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(updateAirportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deleteAirportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(8, Short.MAX_VALUE))))
        );
        airportPanelLayout.setVerticalGroup(
            airportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(airportPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(airportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(airportPanelLayout.createSequentialGroup()
                        .addComponent(airportFilterLabel)
                        .addGap(18, 18, 18)
                        .addGroup(airportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(airportIcaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(airportNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(airportNameLabel)
                            .addComponent(airportIcaoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(airportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(airportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(airportIataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(airportIataLabel))
                            .addGroup(airportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(airportCityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(airportCityLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(airportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(airportCountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(airportCountryLabel)))
                    .addGroup(airportPanelLayout.createSequentialGroup()
                        .addComponent(createAirportButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateAirportButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteAirportButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(applyFilterAirportButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(airportScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainTabbedPane.addTab("Airport", airportPanel);

        AirplanePanel.setBackground(new java.awt.Color(204, 204, 255));

        updateAirplaneButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        updateAirplaneButton.setText("Update selected");
        updateAirplaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAirplaneButtonActionPerformed(evt);
            }
        });

        deleteAirplaneButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        deleteAirplaneButton.setForeground(new java.awt.Color(137, 25, 25));
        deleteAirplaneButton.setText("Delete selected");
        deleteAirplaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAirplaneButtonActionPerformed(evt);
            }
        });

        applyFilterAirplaneButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        applyFilterAirplaneButton.setForeground(new java.awt.Color(25, 62, 137));
        applyFilterAirplaneButton.setText("Apply filter");
        applyFilterAirplaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyFilterAirplaneButtonActionPerformed(evt);
            }
        });

        createAirplaneButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        createAirplaneButton.setText("Create new");
        createAirplaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAirplaneButtonActionPerformed(evt);
            }
        });

        airplaneFilterLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        airplaneFilterLabel.setText("Filter settings for Airplane:");

        airplaneCodeLabel.setText("Code:");

        airplaneAirlineLabel.setText("Airline:");

        airplaneCodeTextField.setBackground(new java.awt.Color(52, 52, 56));
        airplaneCodeTextField.setForeground(new java.awt.Color(255, 255, 255));

        airplaneAirlineTextField.setBackground(new java.awt.Color(52, 52, 56));
        airplaneAirlineTextField.setForeground(new java.awt.Color(255, 255, 255));

        airplaneFuelGreaterLabel.setText("Passenger capacity greater than:");

        airplaneFuelLesserLabel.setText("Passenger capacity lesser than:");

        airplaneLoadingGreaterLabel.setText("Maximum range greater than:");

        airplaneLoadingLesserLabel.setText("Maximum range lesser than:");

        airplanePassengerGreaterTextField.setBackground(new java.awt.Color(52, 52, 56));
        airplanePassengerGreaterTextField.setForeground(new java.awt.Color(255, 255, 255));
        airplanePassengerGreaterTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airplanePassengerGreaterTextFieldActionPerformed(evt);
            }
        });

        airplanePassengerLesserTextField.setBackground(new java.awt.Color(52, 52, 56));
        airplanePassengerLesserTextField.setForeground(new java.awt.Color(255, 255, 255));

        airplaneRangeGreaterTextField.setBackground(new java.awt.Color(52, 52, 56));
        airplaneRangeGreaterTextField.setForeground(new java.awt.Color(255, 255, 255));

        airplaneRangeLesserTextField.setBackground(new java.awt.Color(52, 52, 56));
        airplaneRangeLesserTextField.setForeground(new java.awt.Color(255, 255, 255));

        airplanejList.setBackground(new java.awt.Color(52, 52, 56));
        airplanejList.setForeground(new java.awt.Color(255, 255, 255));
        airplanejList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        airplaneScrollPane.setViewportView(airplanejList);

        javax.swing.GroupLayout AirplanePanelLayout = new javax.swing.GroupLayout(AirplanePanel);
        AirplanePanel.setLayout(AirplanePanelLayout);
        AirplanePanelLayout.setHorizontalGroup(
            AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AirplanePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(airplaneScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AirplanePanelLayout.createSequentialGroup()
                        .addGroup(AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AirplanePanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(airplaneFilterLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(AirplanePanelLayout.createSequentialGroup()
                                .addComponent(airplaneCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(airplaneCodeTextField))
                            .addGroup(AirplanePanelLayout.createSequentialGroup()
                                .addGroup(AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(airplaneFuelGreaterLabel)
                                    .addComponent(airplaneFuelLesserLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(airplanePassengerGreaterTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(airplanePassengerLesserTextField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AirplanePanelLayout.createSequentialGroup()
                                .addComponent(airplaneAirlineLabel)
                                .addGap(31, 31, 31)
                                .addComponent(airplaneAirlineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AirplanePanelLayout.createSequentialGroup()
                                .addGroup(AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(airplaneLoadingGreaterLabel)
                                    .addComponent(airplaneLoadingLesserLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(airplaneRangeLesserTextField)
                                    .addComponent(airplaneRangeGreaterTextField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createAirplaneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(applyFilterAirplaneButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(updateAirplaneButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deleteAirplaneButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        AirplanePanelLayout.setVerticalGroup(
            AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AirplanePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AirplanePanelLayout.createSequentialGroup()
                        .addComponent(airplaneFilterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(airplaneCodeLabel)
                                .addComponent(airplaneCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AirplanePanelLayout.createSequentialGroup()
                                .addGroup(AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(airplaneAirlineLabel)
                                    .addComponent(airplaneAirlineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(airplaneLoadingGreaterLabel)
                                    .addComponent(airplaneRangeGreaterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(airplanePassengerGreaterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(airplaneFuelGreaterLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AirplanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(airplaneLoadingLesserLabel)
                                    .addComponent(airplaneRangeLesserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(airplanePassengerLesserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(airplaneFuelLesserLabel)))))
                    .addGroup(AirplanePanelLayout.createSequentialGroup()
                        .addComponent(createAirplaneButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateAirplaneButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteAirplaneButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(applyFilterAirplaneButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(airplaneScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainTabbedPane.addTab("Airplane", AirplanePanel);

        routePanel.setBackground(new java.awt.Color(204, 204, 255));

        updateRouteButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        updateRouteButton.setText("Update selected");
        updateRouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRouteButtonActionPerformed(evt);
            }
        });

        deleteRouteButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        deleteRouteButton.setForeground(new java.awt.Color(137, 25, 25));
        deleteRouteButton.setText("Delete selected");
        deleteRouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRouteButtonActionPerformed(evt);
            }
        });

        applyFilterRouteButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        applyFilterRouteButton.setForeground(new java.awt.Color(25, 62, 137));
        applyFilterRouteButton.setText("Apply filter");
        applyFilterRouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyFilterRouteButtonActionPerformed(evt);
            }
        });

        createRouteButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        createRouteButton.setText("Create new");
        createRouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRouteButtonActionPerformed(evt);
            }
        });

        routeFilterLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        routeFilterLabel.setText("Filter settings for Route:");

        originFilterLabel.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        originFilterLabel.setText("Origin airport:");

        destinationFilterLabel.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        destinationFilterLabel.setText("Destination airport:");

        routeNameLabel1.setText("Name:");

        routeNameLabel2.setText("Name:");

        routeCityLabel1.setText("City:");

        routeCityLabel2.setText("City:");

        routeNameTextField1.setBackground(new java.awt.Color(52, 52, 56));
        routeNameTextField1.setForeground(new java.awt.Color(255, 255, 255));

        routeCityTextField1.setBackground(new java.awt.Color(52, 52, 56));
        routeCityTextField1.setForeground(new java.awt.Color(255, 255, 255));

        routeNameTextField2.setBackground(new java.awt.Color(52, 52, 56));
        routeNameTextField2.setForeground(new java.awt.Color(255, 255, 255));

        routeCityTextField2.setBackground(new java.awt.Color(52, 52, 56));
        routeCityTextField2.setForeground(new java.awt.Color(255, 255, 255));

        routeIcaoLabel1.setText("ICAO:");

        routeIataLabel1.setText("IATA:");

        routeIcaoLabel2.setText("ICAO:");

        routeIataLabel2.setText("IATA:");

        routeIcaoTextField1.setBackground(new java.awt.Color(52, 52, 56));
        routeIcaoTextField1.setForeground(new java.awt.Color(255, 255, 255));

        routeIataTextField1.setBackground(new java.awt.Color(52, 52, 56));
        routeIataTextField1.setForeground(new java.awt.Color(255, 255, 255));

        routeIataTextField2.setBackground(new java.awt.Color(52, 52, 56));
        routeIataTextField2.setForeground(new java.awt.Color(255, 255, 255));

        routeIcaoTextField2.setBackground(new java.awt.Color(52, 52, 56));
        routeIcaoTextField2.setForeground(new java.awt.Color(255, 255, 255));

        routejList.setBackground(new java.awt.Color(52, 52, 56));
        routejList.setForeground(new java.awt.Color(255, 255, 255));
        routejList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        routeScrollPane.setViewportView(routejList);

        routeCountryLabel1.setText("Country:");

        routeCountryTextField1.setBackground(new java.awt.Color(52, 52, 56));
        routeCountryTextField1.setForeground(new java.awt.Color(255, 255, 255));
        routeCountryTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeCountryTextField1ActionPerformed(evt);
            }
        });

        routeCountryLabel2.setText("Country:");

        routeCountryTextField2.setBackground(new java.awt.Color(52, 52, 56));
        routeCountryTextField2.setForeground(new java.awt.Color(255, 255, 255));
        routeCountryTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeCountryTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout routePanelLayout = new javax.swing.GroupLayout(routePanel);
        routePanel.setLayout(routePanelLayout);
        routePanelLayout.setHorizontalGroup(
            routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(routePanelLayout.createSequentialGroup()
                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(routePanelLayout.createSequentialGroup()
                        .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(routePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(originFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(routePanelLayout.createSequentialGroup()
                                        .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(routeNameLabel1)
                                            .addComponent(routeCityLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(routeCityTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(routeNameTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(routePanelLayout.createSequentialGroup()
                                        .addComponent(routeCountryLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                        .addComponent(routeCountryTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)
                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(routeIcaoLabel1)
                                    .addComponent(routeIataLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(routeIataTextField1)
                                    .addComponent(routeIcaoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(routePanelLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(routeFilterLabel))
                            .addGroup(routePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(routePanelLayout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(routePanelLayout.createSequentialGroup()
                                                .addComponent(routeCountryLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(routeCountryTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(routePanelLayout.createSequentialGroup()
                                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(routeNameLabel2)
                                                    .addComponent(routeCityLabel2))
                                                .addGap(41, 41, 41)
                                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(routeCityTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(routeNameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(41, 41, 41)
                                        .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(routeIcaoLabel2)
                                            .addComponent(routeIataLabel2)))
                                    .addComponent(destinationFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(routeIataTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(routeIcaoTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createRouteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(applyFilterRouteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(updateRouteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deleteRouteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(routePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(routeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        routePanelLayout.setVerticalGroup(
            routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(routePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(routePanelLayout.createSequentialGroup()
                        .addComponent(createRouteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateRouteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteRouteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(applyFilterRouteButton))
                    .addGroup(routePanelLayout.createSequentialGroup()
                        .addComponent(routeFilterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(routePanelLayout.createSequentialGroup()
                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(routeIcaoLabel1)
                                    .addComponent(routeIcaoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(routeIataLabel1)
                                    .addComponent(routeIataTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(routePanelLayout.createSequentialGroup()
                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(originFilterLabel)
                                    .addComponent(routeNameLabel1)
                                    .addComponent(routeNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(routePanelLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(routeCityLabel1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, routePanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(routeCityTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(routeCountryLabel1)
                                    .addComponent(routeCountryTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destinationFilterLabel)
                            .addGroup(routePanelLayout.createSequentialGroup()
                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(routeNameLabel2)
                                    .addComponent(routeNameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(routeCityLabel2)
                                    .addComponent(routeCityTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(routePanelLayout.createSequentialGroup()
                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(routeIcaoLabel2)
                                    .addComponent(routeIcaoTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(routeIataLabel2)
                                    .addComponent(routeIataTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(routeCountryLabel2)
                            .addComponent(routeCountryTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(routeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainTabbedPane.addTab("Route", routePanel);

        jButton1.setText("Run Client Demo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clientDemoPanelLayout = new javax.swing.GroupLayout(clientDemoPanel);
        clientDemoPanel.setLayout(clientDemoPanelLayout);
        clientDemoPanelLayout.setHorizontalGroup(
            clientDemoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDemoPanelLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        clientDemoPanelLayout.setVerticalGroup(
            clientDemoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDemoPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(371, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Client Demo", clientDemoPanel);

        warningLabel.setForeground(new java.awt.Color(204, 0, 0));
        warningLabel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(warningLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAirportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAirportButtonActionPerformed
        AirportAttributesDialog airportAttributesDialog = new AirportAttributesDialog(this, true, mgProvider);
        DialogDesigner.centerDialog(airportAttributesDialog);
        updateLists();
    }//GEN-LAST:event_createAirportButtonActionPerformed

    private void updateAirportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAirportButtonActionPerformed
        //send id
        AirportAttributesDialog airportAttributesDialog = new AirportAttributesDialog(this, true, mgProvider, airportjList.getSelectedValue());
        DialogDesigner.centerDialog(airportAttributesDialog);
        updateLists();
    }//GEN-LAST:event_updateAirportButtonActionPerformed

    private void airportNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airportNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airportNameTextFieldActionPerformed

    private void deleteAirportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAirportButtonActionPerformed
        warningLabel.setText(" ");
        try {
            mgProvider.getRelationService().deleteAirport((Airport) airportjList.getSelectedValue());
        } catch (InvalidAttributeException ex) {
            warningLabel.setText(ex.getMessage());
        }
        updateAirportList();
    }//GEN-LAST:event_deleteAirportButtonActionPerformed

    private void createRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRouteButtonActionPerformed
        RouteAttributesDialog attributesDialog = new RouteAttributesDialog(this, true, mgProvider);
        DialogDesigner.centerDialog(attributesDialog);
        updateLists();
    }//GEN-LAST:event_createRouteButtonActionPerformed

    private void deleteRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRouteButtonActionPerformed
        warningLabel.setText(" ");
        try {
            mgProvider.getRelationService().deleteRoute((Route) routejList.getSelectedValue());
        } catch (InvalidAttributeException e) {
            warningLabel.setText(e.getMessage());
        }
        updateRouteList();
    }//GEN-LAST:event_deleteRouteButtonActionPerformed

    private void updateRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRouteButtonActionPerformed
        //id must be set
        RouteAttributesDialog attributesDialog = new RouteAttributesDialog(this, true, mgProvider, routejList.getSelectedValue());
        DialogDesigner.centerDialog(attributesDialog);
        updateLists();
    }//GEN-LAST:event_updateRouteButtonActionPerformed

    private void airportCityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airportCityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airportCityTextFieldActionPerformed

    private void airportIataTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airportIataTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airportIataTextFieldActionPerformed

    private void createAirplaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAirplaneButtonActionPerformed
        AirplaneAttributesDialog attributesDialog = new AirplaneAttributesDialog(this, true, mgProvider);
        DialogDesigner.centerDialog(attributesDialog);
        updateLists();
    }//GEN-LAST:event_createAirplaneButtonActionPerformed

    private void deleteAirplaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAirplaneButtonActionPerformed
        warningLabel.setText(" ");
        try {
            mgProvider.getRelationService().deleteAirplane((Airplane) airplanejList.getSelectedValue());
        } catch (InvalidAttributeException e) {
            warningLabel.setText(e.getMessage());
        }
        updateAirplaneList();
    }//GEN-LAST:event_deleteAirplaneButtonActionPerformed

    private void updateAirplaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAirplaneButtonActionPerformed
        //send airplane id
        AirplaneAttributesDialog attributesDialog = new AirplaneAttributesDialog(this, true, mgProvider, airplanejList.getSelectedValue());
        DialogDesigner.centerDialog(attributesDialog);
        updateLists();
    }//GEN-LAST:event_updateAirplaneButtonActionPerformed

    private void airportCountryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airportCountryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airportCountryTextFieldActionPerformed

    private void routeCountryTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeCountryTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routeCountryTextField1ActionPerformed

    private void routeCountryTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeCountryTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routeCountryTextField2ActionPerformed

    private void applyFilterRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyFilterRouteButtonActionPerformed
        warningLabel.setText(" ");
        name1 = Utils.emptyStringToNull(routeNameTextField1);
        name2 = Utils.emptyStringToNull(routeNameTextField2);
        city1 = Utils.emptyStringToNull(routeCityTextField1);
        city2 = Utils.emptyStringToNull(routeCityTextField2);
        country1 = Utils.emptyStringToNull(routeCountryTextField1);
        country2 = Utils.emptyStringToNull(routeCountryTextField2);
        iata1 = Utils.emptyStringToNull(routeIataTextField1);
        iata2 = Utils.emptyStringToNull(routeIataTextField2);
        icao1 = Utils.emptyStringToNull(routeIcaoTextField1);
        icao2 = Utils.emptyStringToNull(routeIcaoTextField2);
        updateRouteList();
    }//GEN-LAST:event_applyFilterRouteButtonActionPerformed

    private void applyFilterAirplaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyFilterAirplaneButtonActionPerformed
        warningLabel.setText(" ");
        try {
            filterCode = Utils.emptyStringToNull(airplaneCodeTextField);
            filterAirline = Utils.emptyStringToNull(airplaneAirlineTextField);
            filterMaxPassengerCapacity = Utils.emptyStringToNullConvert(airplanePassengerGreaterTextField);
            filterMinPassengerCapacity = Utils.emptyStringToNullConvert(airplanePassengerLesserTextField);
            filterMaxMaximumRange = Utils.emptyStringToNullConvert(airplaneRangeGreaterTextField);
            filterMinMaximumRange = Utils.emptyStringToNullConvert(airplaneRangeLesserTextField);
            updateAirplaneList();
        } catch (NumberFormatException e) {
            warningLabel.setText("Input is not and integer.");
        }
    }//GEN-LAST:event_applyFilterAirplaneButtonActionPerformed

    private void applyFilterAirportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyFilterAirportButtonActionPerformed
        warningLabel.setText(" ");
        name = Utils.emptyStringToNull(airportNameTextField);
        city = Utils.emptyStringToNull(airportCityTextField);
        country = Utils.emptyStringToNull(airportCountryTextField);
        iata = Utils.emptyStringToNull(airportIataTextField);
        icao = Utils.emptyStringToNull(airportIcaoTextField);
        updateAirportList();
    }//GEN-LAST:event_applyFilterAirportButtonActionPerformed

    private void airplanePassengerGreaterTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airplanePassengerGreaterTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airplanePassengerGreaterTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ClientDemoFrame clientDemoFrame = new ClientDemoFrame();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.alee.laf.WebLookAndFeel");
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
             if ("Nimbus".equals(info.getName())) {
             javax.swing.UIManager.setLookAndFeel(info.getClassName());
             break;
             }
             }*/
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AirplanePanel;
    private javax.swing.JLabel airplaneAirlineLabel;
    private javax.swing.JTextField airplaneAirlineTextField;
    private javax.swing.JLabel airplaneCodeLabel;
    private javax.swing.JTextField airplaneCodeTextField;
    private javax.swing.JLabel airplaneFilterLabel;
    private javax.swing.JLabel airplaneFuelGreaterLabel;
    private javax.swing.JLabel airplaneFuelLesserLabel;
    private javax.swing.JLabel airplaneLoadingGreaterLabel;
    private javax.swing.JLabel airplaneLoadingLesserLabel;
    private javax.swing.JTextField airplanePassengerGreaterTextField;
    private javax.swing.JTextField airplanePassengerLesserTextField;
    private javax.swing.JTextField airplaneRangeGreaterTextField;
    private javax.swing.JTextField airplaneRangeLesserTextField;
    private javax.swing.JScrollPane airplaneScrollPane;
    private javax.swing.JList airplanejList;
    private javax.swing.JLabel airportCityLabel;
    private javax.swing.JTextField airportCityTextField;
    private javax.swing.JLabel airportCountryLabel;
    private javax.swing.JTextField airportCountryTextField;
    private javax.swing.JLabel airportFilterLabel;
    private javax.swing.JLabel airportIataLabel;
    private javax.swing.JTextField airportIataTextField;
    private javax.swing.JLabel airportIcaoLabel;
    private javax.swing.JTextField airportIcaoTextField;
    private javax.swing.JLabel airportNameLabel;
    private javax.swing.JTextField airportNameTextField;
    private javax.swing.JPanel airportPanel;
    private javax.swing.JScrollPane airportScrollPane;
    private javax.swing.JList airportjList;
    private javax.swing.JButton applyFilterAirplaneButton;
    private javax.swing.JButton applyFilterAirportButton;
    private javax.swing.JButton applyFilterRouteButton;
    private javax.swing.JPanel clientDemoPanel;
    private javax.swing.JButton createAirplaneButton;
    private javax.swing.JButton createAirportButton;
    private javax.swing.JButton createRouteButton;
    private javax.swing.JButton deleteAirplaneButton;
    private javax.swing.JButton deleteAirportButton;
    private javax.swing.JButton deleteRouteButton;
    private javax.swing.JLabel destinationFilterLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JLabel originFilterLabel;
    private javax.swing.JLabel routeCityLabel1;
    private javax.swing.JLabel routeCityLabel2;
    private javax.swing.JTextField routeCityTextField1;
    private javax.swing.JTextField routeCityTextField2;
    private javax.swing.JLabel routeCountryLabel1;
    private javax.swing.JLabel routeCountryLabel2;
    private javax.swing.JTextField routeCountryTextField1;
    private javax.swing.JTextField routeCountryTextField2;
    private javax.swing.JLabel routeFilterLabel;
    private javax.swing.JLabel routeIataLabel1;
    private javax.swing.JLabel routeIataLabel2;
    private javax.swing.JTextField routeIataTextField1;
    private javax.swing.JTextField routeIataTextField2;
    private javax.swing.JLabel routeIcaoLabel1;
    private javax.swing.JLabel routeIcaoLabel2;
    private javax.swing.JTextField routeIcaoTextField1;
    private javax.swing.JTextField routeIcaoTextField2;
    private javax.swing.JLabel routeNameLabel1;
    private javax.swing.JLabel routeNameLabel2;
    private javax.swing.JTextField routeNameTextField1;
    private javax.swing.JTextField routeNameTextField2;
    private javax.swing.JPanel routePanel;
    private javax.swing.JScrollPane routeScrollPane;
    private javax.swing.JList routejList;
    private javax.swing.JButton updateAirplaneButton;
    private javax.swing.JButton updateAirportButton;
    private javax.swing.JButton updateRouteButton;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
